version: '3.7'

services:
  work_flow_client:
    image: work_flow_client:dev
    container_name: work_flow_client_dev
    ports:
      - "8000:8000"
    environment:
      - FLASK_BACKEND_URL=http://work_flow_server:16666
      - NODE_ENV=development
    volumes:
      - ..:/app
      - workflow_node_modules:/app/node_modules
    networks:
      - redis-network
    command: /bin/sh -c "npm install @utoo/pack-linux-x64-gnu --registry=https://registry.npmmirror.com && npm run dev"
    restart: unless-stopped

networks:
  redis-network:
    external: true

volumes:
  workflow_node_modules:
